version: "3.8"
services:
  twlhelper:
    image: ghcr.io/ds-homebrew/twlhelper
    volumes:
      - ./data:/home/twlhelper/data
    secrets:
      - twlhelper-settings
    restart: unless-stopped

secrets:
  twlhelper-settings:
    file: ./settings.json
