name: 'Push to main'

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send job start webhook
        continue-on-error: true
        uses: appleboy/discord-action@3c62873803ab2f276e28cdde23972899fb26e3a5
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Starting build for commit <https://github.com/${{ github.repository }}/commit/${{ github.sha }}> by ${{ github.actor }}
            >>> ${{ github.event.head_commit.message }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Check with flake8
        run: |
          flake8 . --ignore=E501
      - name: Reboot TWLHelper
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./twlhelper-reboot.sh
            exit
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
      - name: Send webhook on failure
        if: ${{ failure() }}
        continue-on-error: true
        uses: appleboy/discord-action@3c62873803ab2f276e28cdde23972899fb26e3a5
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Failed to build <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>
      - name: Send webhook on cancellation
        if: ${{ cancelled() }}
        continue-on-error: true
        uses: appleboy/discord-action@3c62873803ab2f276e28cdde23972899fb26e3a5
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Cancelled build for <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>
