name: 'Push to main'

on:
  push:
    branches: main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
      - name: Send job start webhook
        continue-on-error: true
        uses: appleboy/discord-action@3c62873803ab2f276e28cdde23972899fb26e3a5
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Starting build for commit <https://github.com/${{ github.repository }}/commit/${{ github.sha }}> by ${{ github.actor }}
            >>> ${{ github.event.head_commit.message }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Check with flake8
        run: |
          flake8 . --ignore=E501,E722,E126,E128,W503,E121 --exclude=migrations
      - name: Reboot TWLHelper
        uses: fifsky/ssh-action@master
        with:
          command: |
            echo Rebooting bot...
            cd TWLHelper
            git pull
            kill -9 $(cat twlhelper.pid)
            pip install -r requirements.txt
            nohup ./twlhelper.py & echo $! > twlhelper.pid
            sleep 3
            echo Success.
            exit
          host: ${{ secrets.SSH_HOST }}
          user: twlhelper
          pass: ${{ secrets.SSH_PRIVATE_KEY}}
      - name: Send webhook on failure
        if: ${{ failure() }}
        continue-on-error: true
        uses: appleboy/discord-action@3c62873803ab2f276e28cdde23972899fb26e3a5
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Failed to build <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>
      - name: Send webhook on cancellation
        if: ${{ cancelled() }}
        continue-on-error: true
        uses: appleboy/discord-action@3c62873803ab2f276e28cdde23972899fb26e3a5
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: |
            Cancelled build for <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>